name = "ologic_config_capacitor"

# Anything in the [required] table can't be empty by definition. If it has to be
# a specific value, then that is specified

# Type checking
# @STRING_NONEMPTY is a directive to check for a string type and compare against a regualr expression that will match any string that contains at least one non-whitespace character.
# @STRING_ANY is a directive to check for a string type and compare against a regualr expression that will match any string.
# @STRING_PATH is a directive to check for a string type and validate it as a path to a real file
# @NUMBER_GTE_ZERO is a directive to check for a numerical type (int or floar) and validate that it is greater than or equal to zero

[component.name]
required = true
allow_multiples = false
accepted_values = ["@STRING_NONEMPTY"]

[component.description]
required = true
allow_multiples = false
accepted_values = ["@STRING_NONEMPTY"]

[component.lifecycle_state]
required = true
allow_multiples = false
accepted_values = ["untested", "prototype", "rocksolid", "garbage"]

[component.category]
required = true
allow_multiples = false
accepted_values = ["capacitor"]

[component.external_file]
required = true
allow_multiples = true

    [component.external_file.document]
    required = false
    allow_multiples = true

        [component.external_file.document.name]
        required = true
        allow_multiples = false
        accepted_values = ["@STRING_NONEMPTY"]

        [component.external_file.document.path]
        required = true
        allow_multiples = false
        accepted_values = ["@STRING_PATH"]

    [component.external_file.footprint]
    required = true
    allow_multiples = true

        [component.external_file.footprint.name]
        required = true
        allow_multiples = false
        accepted_values = ["@STRING_NONEMPTY"]

        [component.external_file.footprint.path]
        required = true
        allow_multiples = false
        accepted_values = ["@STRING_PATH"]

    [component.external_file.symbol]
    required = true
    allow_multiples = false

        [component.external_file.symbol.name]
        required = true
        allow_multiples = false
        accepted_values = ["@STRING_NONEMPTY"]

        [component.external_file.symbol.path]
        required = true
        allow_multiples = false
        accepted_values = ["@STRING_PATH"]

[component.parameter]
    required = true
    allow_multiples = true

    [component.parameter.capacitance]
    required = true
    allow_multiples = false

        [component.parameter.capacitance.value]
        required = true
        allow_multiples = false
        accepted_values = ["@NUMBER_GTE_ZERO"]

        [component.parameter.capacitance.unit]
        required = true
        allow_multiples = false
        accepted_values = ["F", "uF", "pF"]

        [component.parameter.capacitance.visible]
        required = true
        allow_multiples = false
        accepted_values = [true, false]

    
    [component.parameter.tolerance]
    required = true
    allow_multiples = false

        [component.parameter.tolerance.value]
        required = true
        allow_multiples = false
        accepted_values = ["@NUMBER_GTE_ZERO"]

        [component.parameter.tolerance.unit]
        required = true
        allow_multiples = false
        accepted_values = ["%", "ppm"]
    
        [component.parameter.tolerance.visible]
        required = true
        allow_multiples = false
        accepted_values = [true, false]

    [component.parameter.temp_coef]
    required = true
    allow_multiples = false

        [component.parameter.temp_coef.value]
        required = true
        allow_multiples = false
        accepted_values = ["C0G", "NP0", "X5R", "X7R"]

        [component.parameter.temp_coef.unit]
        required = false
        allow_multiples = false
        accepted_values = [""]
    
        [component.parameter.temp_coef.visible]
        required = true
        allow_multiples = false
        accepted_values = [true, false]

    [component.parameter.voltage]
    required = true
    allow_multiples = false

        [component.parameter.voltage.value]
        required = true
        allow_multiples = false
        accepted_values = "@NUMBER_GTE_ZERO"
        
        [component.parameter.voltage.unit]
        required = true
        allow_multiples = false
        accepted_values = ["V"]
        
        [component.parameter.voltage.visible]
        required = true
        allow_multiples = false
        accepted_values = [true, false]
    
    [component.parameter.package]
    required = true
    allow_multiples = false

        # This list can probably get smaller....
        [component.parameter.package.value]
        required = true
        allow_multiples = false
        accepted_values = [
            "0201 (M0603)",
            "0202 (M0505)",
            "0204 (M0510)",
            "0306 (M0816)",
            "0402 (M1005)",
            "0502 (M1406)",
            "0504 (M1210)",
            "0505 (M1313)",
            "0508 (M1220)",
            "0603 (M1608)",
            "0612 (M1632)",
            "0709 (M1823)",
            "0805 (M2012)",
            "01005 (M0402)",
            "1005 (M2512)",
            "1111 (M2828)",
            "1206 (M3216)",
            "1210 (M3225)",
            "1410 (M3524)",
            "1410 (M3727)",
            "1805 (M4512)",
            "1808 (M4520)",
            "1810 (M4525)",
            "1812 (M4532)",
            "1825 (M4564)",
            "2008 (M5020)",
            "2012 (M5030)",
            "2211 (M5728)",
            "2215 (M5738)",
            "2220 (M5750)",
            "2225 (M5763)",
            "2325 (M5864)",
            "2520 (M5650)",
            "2520 (M6450)",
            "2525 (M6464)",
            "2824 (M7260)",
            "3025 (M7563)",
            "3040 (M7610)",
            "3640 (M9110)",
            "3838 (M9797)",
            "4044 (M1011)",
            "008004 (M0201)",
            "015008 (M05025)"]

        [component.parameter.package.unit]
        # The unit is not required for this parameter,
        # but if it is, it must be equal to an empty string
        required = false
        allow_multiples = false
        accepted_values = [""]

        [component.parameter.package.visible]
        required = true
        allow_multiples = false
        accepted_values = [true, false]

    [component.parameter.mounting_type]
    required = true
    allow_multiples = false

        [component.parameter.mounting_type.value]
        required = true
        allow_multiples = false
        accepted_values = ["SMD", "TH"]

        [component.parameter.mounting_type.unit]
        required = false
        allow_multiples = false
        accepted_values = [""]

        [component.parameter.mounting_type.visible]
        required = true
        allow_multiples = false
        accepted_values = [true, false]

    [component.parameter.manufacturer]
    required = false
    allow_multiples = false

        [component.parameter.manufacturer.value]
        required = true
        allow_multiples = false
        accepted_values = [
            "Vishay", 
            "KEMET",
            "Knowles",
            "Samsung",
            "Panasonic"]
        
        [component.parameter.manufacturer.unit]
        required = false
        allow_multiples = false
        accepted_values = [""]

        [component.parameter.manufacturer.visible]
        required = true
        allow_multiples = false
        accepted_values = [true, false]

    [component.parameter.height]
    required = false
    allow_multiples = false

        [component.parameter.height.value]
        required = true
        allow_multiples = false
        accepted_values = ["@NUMBER_GTE_ZERO"]

        [component.parameter.height.unit]
        required = true
        allow_multiples = false
        accepted_values = ["in", "mm", "mil"]

        [component.parameter.height.visible]
        required = true
        allow_multiples = false
        accepted_values = [true, false]