name = "RES_10K_0.1%_63mW_0402_Thin_50ppm_-55-155C"
type = "resistor"
generic = true
symbol = "models/sch/res.SchLib"

[physical]
    
  footprint = "models/sch/RESC0402.PcbLib"
  package = "0402 (1005 Metric)"
  
  [dims]
    [dims.height]
      value = 0.35
      unit = "mm"
    [dims.length]
      value = 1
      unit = "mm"
    [dims.width]
      value = 0.5
      unit = "mm"

[resistance]
  value = 10000.0
  unit = "Ω"

[tolerance]
  value = 0.1
  unit = "%"

[power]
  value = 0.063
  unit = "W"

composition = "thin film"
  
[temp_coeff]
  value = 50.0
  unit = "ppm/°C"

[oper_temp]

  [oper_temp.min]
    value = -55.0
    unit = "°C"

  [oper_temp.max]
    value = 155.0
    unit = "°C"