name = "RES_10K_0.1%_63mW_0402_Thin_50ppm_-55-155C"
type = "resistor"

# Required for Altium. how do i specify a variable path?
[models]
  symbol = "$MODELS/sch/res.SchLib"
  footprint = "$MODELS/pcb/RESC0402.PcbLib"

# This parameter is going to need some lovin'
# It should be able to support a _list_ of **EQUIVALENT** packages
[param.package]
  value = "0402 (1005 Metric)"
  unit = ""

[param.dims.length]
  value = 9999
  unit = "mm"

[param.dims.width]
  value = 9999
  unit = "mm"

[param.dims.height]
  value = 9999
  unit = "mm"

[param.resistance]
  value = 10000
  unit = "ohm"

[param.tolerance]
  value = 0.1
  unit = "%"

[param.power]
  value = 0.063
  unit = "W"

[param.composition]
  value = "Thin Film"
  unit = ""
  
[param.temp.min]
  value = -55.0
  unit = "C"

[param.temp.max]
    value = 155.0
    unit = "C"

[param.temp.coeff]
  value = 50.0
  unit = "ppm/C"

