# http://www.jst-mfg.com/product/pdf/eng/eNSH.pdf


[[parameter]]
name = "Manufacturer"
value = "JST"

[[parameter]]
name = "Manufacturer Part Number"
value = "BM02B-NSHSS-TBT"

[[parameter]]
name = "Entry Type"
value = "Top"

[[parameter]]
name = "Circuits"
value = 2
unit = ""

[[parameter]]
name = "pitch"
value = 1.0
unit = "mm"

[[parameter]]
name = "current rating"
value = 1.0
unit = "A"

[[parameter]]
name = "voltage rating"
value = 50
unit = "V"