name        = "CAP CER 10µF 10% 25V X7R SMD 1210 (M3225)"
description = "CAP CER 10µF 10% 25V X7R SMD 1210 (M3225)"
category    = "capacitor/ceramic"
lifecycle   = "untested"

[external]

    [external.symbol]
    name = "CAP2_NONPOL"
    path = "symbols/CAP2_NONPOL.SchLib"

    [[external.footprint]]
    name = "CAP_CHIP_0805(M2012)_L"
    path = "footprints/CAP_CHIP_1210(M3225)_L.PcbLib"

    [[external.footprint]]
    name = "CAP_CHIP_0805(M2012)_N"
    path = "footprints/CAP_CHIP_1210(M3225)_N.PcbLib"

[parameters]

    [parameters.dielectric]
    value = "Ceramic"
    visible = false

    [parameters.capacitance]
    value = 10.0
    unit = "µF"
    visible = true

    [parameters.tolerance]
    value = 10.0
    unit = "%"
    visible = false

    [parameters.voltage]
    value = 25.0
    unit = "V"
    visible = true

    [parameters.temp_coeff]
    value = "X7R"
    visible = false

    [parameters.mounting_type]
    value = "SMD"
    visible = false

    [parameters.package]
    value = "1210 (M3225)"
    visible = true