#config 		= "ologic_config_resistor"

name		= "RES 100K 1% 0.063W SMD 0402 (M1005) Thin Film"
description	= "RES 100K 1% 0.063W SMD 0402 (M1005) Thin Film"
category	= "resistor/single."
lifecycle	= "untested"

[external]

	[external.symbol]
	name = "RES2"
	path = "symbols/RES2.SchLib"

	[[external.footprint]]
	name = "RESC0402_L"
	path = "footprints/RESC0402_L.PcbLib"

	[[external.footprint]]
	name = "RESC0402_N"
	path = "footprints/RESC0402_N.PcbLib"

	[[external.document]]
	name = "AN: Using Laser Trimmable Resistors"
	path = "./doc/vishay-laser-trimmable-res.pdf"

	[[external.document]]
	name = "AN: Frequency Response of Thin Film Chip Resistors"
	path = "./doc/vishay-thin-res-freq-response.pdf"

	[[external.url]]
	name = "Wikipedia"
	path = "https://en.wikipedia.org/wiki/Resistor"

	[[external.url]]
	name = "Vishay Resistor AN Library"
	path = "https://www.vishay.com/how/onlineliterature/technical-library/#Resistors,%20Fixed,%20Thick%20film"

[parameters]

	[parameters.resistance]
	value = 100000.0
	unit = "Î©"
	visible = true

	[parameters.tolerance]
	value = 1.0
	unit = "%"
	visible = false

	[parameters.power]
	value = 0.063
	unit = "W"
	visible = false

	[parameters.mounting_type]
	value = "SMD"
	visible = false

	[parameters.package]
	value = "0402 (M1005)"
	visible = false

	[parameters.composition]
	value = "Thin Film"
	visible = false